### ISSUE TITLE
Presign URL not refreshing for same file within same day.

### ISSUE THREAD

**Issue by meenakshidua** [jthomas/serverless-file-storage#2]
Hello James,
When I try to regenerate the presign URL for same object name after it expires, it does not change for the same day.
As a business requirement I need to update the object within same day, due to same presignURL I'm unable to overwrite the object after 300s and same date.
Can you please assist, if this can be done in nodejs.

Thank you,

**Comment by jthomas** [comment]
Change this configuration parameter to the desired expiration time.
https://github.com/jthomas/serverless-file-storage/blob/master/nodejs/presign/presign.js#L32

**Comment by meenakshidua** [comment]
Thanks James, I've tried changing Expires: 300 to a constant or random value but presign URL remains same in Cloud function - nodejs api response.
Do you recommend to keep presign valid for 24 hours?
