### ISSUE TITLE
Unable to overwrite the file within same day using SignedURL once initial Expires interval is over

### ISSUE THREAD

**Issue by meenakshidua** [jthomas/serverless-file-storage#3]
client.getSignedUrl('putObject', options) returning Expired URL for the entire day, after initial Expires: 300 interval is exceeded. 
I can not exceed initial Expires interval to entire day, as this may lead to security concern. Is there a way to overwrite the same file during same day using signed URL after initial defined Expires time is over.

**Comment by jthomas** [comment]
There is no way to update a file once the expired time has elapsed. You will need to either re-call the API to generate a new pre-signed URL or increase the expiry period.
